FROM httpd:2.4-alpine

RUN apk update && apk upgrade

# Copia la configuración
COPY apache-vhost.conf /usr/local/apache2/conf/apache-vhost.conf
RUN echo "Include /usr/local/apache2/conf/apache-vhost.conf" >> /usr/local/apache2/conf/httpd.conf

# Instala utilidades si quieres
RUN apk add --no-cache bash